config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root to: 'home#index'

  resources :parts_lists, except: [:show]

  resources :builds, except: [:index] do
    get :index, on: :collection, :action => 'index_all'
  end

  resources :builds do
    resources :comments
  end

  resources :builds do
    resources :users do
      post "like",      to: "likes#create"
      delete "dislike", to: "likes#destroy"
    end 
  end

  resources :users do 
    resources :parts_lists, only: [:show, :index, :new, :edit, :update, :destroy]
    resources :builds, except: [:index] do
      get :index, on: :collection, :action => 'index_builds'
    end
  end

end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :user
  belongs_to :parts_list, dependent: :destroy

  has_many_attached :images

  has_many :comments

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  validates :title,          presence: true
  validates :description,    presence: true
  validates :parts_list_id,  presence: true

  def first_image
    images.first
  end
  
  def other_images
    images.drop(images.first.id)
  end

  def self.featured
    most_liked.first
  end
  
  scope :most_liked,  ->{ order("likes_count DESC")}
  scope :newest,      ->{ order("created_at DESC")}
  scope :oldest,      ->{ order("created_at ASC")}
  
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_build, only: [:show, :edit, :update, :destroy]
  before_action :need_parts_list_to_build, only: [:new]

  def index_all
    @builds = Build.send(params[:search])
    render :all
  end
  
  def index_builds
    @user = User.find_by(id: params[:user_id])
    @builds = Build.find_by(id: params[:id])
    render :index
  end

  def show
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @build }
    end
  end

  def new
    @build = Build.new
  end

  def create
    @build = current_user.builds.new(build_params)
    if @build.save
      redirect_to(user_builds_path(current_user), flash: { success: "Build Created!" })
    else      
      redirect_to(new_user_build_path(current_user), flash: { message: "Something went wrong, try again!" })
    end
  end

  def edit
  end

  def update
    if @build.user == current_user
      @build.update(build_params)
      if @build.save
        redirect_to(user_builds_path(current_user), flash: { success: "Your Build #{@build.title} was successfully updated!" })
      else
        redirect_to(edit_user_build_path(current_user, @build), flash: { message: "Something went wrong, try again!" })
      end
    else
      flash[:message] = "You don't have permission to do that"
      redirect_to root_path
    end
  end

  def destroy
    if @build.user == current_user
      @build.delete
      flash[:success] = "Build deleted!"
      redirect_to user_builds_path(current_user)
    else
      flash.now[:message] = "You don't have permision to do that!"
      redirect_to root_path
    end
  end

  private

    def build_params
      params.require(:build).permit(
        :title,
        :description,
        :parts_list_id,
        images: []
      )
    end

    def find_build
      @build = Build.find_by_id(params[:id])
    end

    def need_parts_list_to_build
      if current_user.has_no_parts?
        redirect_to user_parts_lists_path
      else
        @build = current_user.builds.new
      end
    end

end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_build_index_card.html.erb
<div class="card">
<%= link_to image_tag(build.images.first, class: "card-img"), build_path(build) %></img>
  <div class="card-header text-center">
    <h4 class="text-muted"><%= link_to build.title, build_path(build) %></h4>
    <%= build.likes_count %> <i class="fa fa-heart"></i>
  </div>
  <div class="card-body">
    <ul class="list-group">
      <li class="list-group-item clearfix">
        <span class="badge badge badge-secondary">CPU</span>
        <label><%= build.parts_list.cpu %></label>
        <span class="badge badge badge-secondary">GPU</span>
        <label><%= build.parts_list.video_card %></label>
        <span class="badge badge badge-secondary">MB</span>
        <label><%= build.parts_list.motherboard %></label>
        <span class="badge badge badge-secondary">RAM</span>
        <label><%= build.parts_list.ram %></label>
        <span class="badge badge badge-secondary">OS</span>
        <label><%= build.parts_list.operating_system %></label>
        <span class="badge badge badge-secondary">
        </span>
        <span class="pull-right">
          <% if build.user != current_user %>
            <%= render 'like_unlike_button', build: build %>
          <% end %>
        </span>
    </ul>
  </div>
  <div class="card-footer text-center">
    <small class="text-muted">Last updated <%= build.created_at.to_date %> by 
      <%= link_to build.user.username.capitalize, user_path(build.user) %>
    </small>                
  </div>
</div><br>

app/views/builds/_builds_deck.html.erb
<nav class="navbar justify-content-end">
    <h3 class="text-xs-center m-y-3 text-white"><%= @user.username.capitalize %> Builds</h3>    
    <%= link_to "Parts Lists", user_parts_lists_path(current_user), class: 'btn btn-success ml-auto mr-2 font-weight-bold' %>
    <%= link_to "Start A New Build", new_user_build_path(current_user), class: 'btn btn-info mr-2 font-weight-bold' %>
</nav>

<% current_user.builds.each_slice(2) do |builds| %>       
  <div class="card-deck ">
    <% builds.each do |b| %>

      <div class="card">
      <%= link_to image_tag(b.images.first, class: "card-img"), build_path(b) %>
        <div class="card-header text-center">
          <h4 class="text-muted"><%= b.title %></h4> 
          <div class="btn-group">                  
            <%= link_to "Edit", edit_user_build_path(current_user, b), class: 'btn btn-primary active' %>
            <%= link_to "Delete", b, method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: 'btn btn-secondary btn-danger' %>                  
          </div>
        </div>
        <div class="card-body">
          <ul class="list-group">
            <li class="list-group-item">
              <span class="badge badge badge-secondary">CPU</span>
              <label><%= b.parts_list.cpu %></label>
            </li>
            <li class="list-group-item">
              <span class="badge badge badge-secondary">GPU</span>
              <label><%= b.parts_list.video_card %></label>
            </li>
          </ul>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted">Last updated <%= b.created_at.to_date %></small>                
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/builds/_builds_jumbotron.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">Start your first build</h1>
  <p class="lead">Tip: Fill out your builds description, What do you use the machine for? What worked well? Any problems?</p>
  <hr class="my-4">
  <p>Get Started here</p>
  <%= link_to "New Build", new_user_build_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/builds/_form.html.erb
<%= form_for @build do |f| %>
  <form class="form-horizontal">
    <div class="form-group row text-white">
      <%= f.label :title, class: "col-sm-3 col-form-label" %>
      <%= f.text_field :title, class: "form-control col-sm-9" %>  
    </div>    
    <div class="form-group row text-white">
      <%= f.label :description, class: "col-sm-3 col-form-label" %>
      <%= f.text_area :description, rows: 7, class: "form-control col-sm-9", prompt: "What do you use the machine for? What worked well? Any problems?" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :parts_list, class: "col-sm-3 col-form-label" %>
      <%= f.collection_select :parts_list_id, current_user.parts_lists, :id, :name, class: "form-control col-sm-9", prompt: "Choose a parts list..." %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :images, class: "col-sm-3 col-form-label" %>
      <%= f.file_field :images, multiple: true, class: "form-control-file col-sm-9" %>
    </div>
    <div class="text-center">
      <%= f.submit class: 'btn-primary btn' %>
    </div>
  </form>      
<% end %>

app/views/builds/_like_unlike_button.html.erb
  <div class="container text-center">
    <% if build.likers.exclude? current_user %>
      <%= button_to build_user_like_path(build, current_user), class: "btn btn-outline-danger like-build", :remote => true, :method => :post do %>
      Like <i class="fa fa-heart"></i>
      <% end %>
    <% else %>
      <%= button_to build_user_dislike_path(build, current_user), class: "btn btn-outline-danger dislike-build", :remote => true, :method => :delete do %>
      Unlike <i class="fa fa-thumbs-down"></i>
      <% end %>
    <% end %>
  </div>

app/views/builds/_sort_by.html.erb
  <strong>Sort by</strong><br>
    <%= link_to "Newest", builds_path(search: "newest") %> |
    <%= link_to "Oldest", builds_path(search: "oldest") %> |
    <%= link_to "Most Liked", builds_path(search: "most_liked") %>
  </div>

app/views/builds/all.html.erb
<div class="container">
<nav class="navbar justify-content-end">
    <h3 class="text-xs-center m-y-3 text-white">Completed Builds</h3>    
</nav>

<%= render 'sort_by' %>

<%= render :partial => 'build_index_card', :collection => @builds, :as => 'build' %>

</div>

app/views/builds/edit.html.erb
<div class="container text-center">
  <h1>Edit <%= @build.title %> Build</h1>
</div>

<%= render 'form' %>

app/views/builds/index.html.erb
<div class="container">

  <% if current_user.has_no_parts? %>
    <nav class="navbar justify-content-end">
      <h3 class="text-xs-center m-y-3 text-muted"><%= @user.username.capitalize %> Builds</h3>   
    </nav>
    <%= render 'parts_lists/jumbotron'%>
  <% elsif current_user.has_no_builds? %>
    <nav class="navbar justify-content-end">
      <h3 class="text-xs-center m-y-3 text-muted"><%= @user.username.capitalize %> Builds</h3>   
    </nav>
    <%= render 'builds_jumbotron' %>

  <% else %>
    <%= render 'builds_deck' %>
  <% end %>

</div>

app/views/builds/new.html.erb
<div class="container text-center text-secondary">
  <h1>New Build</h1>
</div>

<%= render 'form' %>

app/views/builds/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <h1 class="name text-primary"><%= @build.title %></h1><br>
    by <%= link_to @build.user.username.capitalize, user_path(@build.user) %>
  </div>
</div>
<div class="card-group">
  <div class="card col-sm-6">
  <%= image_tag(@build.first_image, class: "card-img") %></img>
    <div class="card">
      <% @build.other_images.each_slice(2) do |two_images| %>
        <div class="card-group">
          <% two_images.each do |image| %>
            <%= image_tag(image, class: "card card-img") %>
          <% end %>
        </div>
      <% end %>
    </div>

    <ul class="list-group text-center">
    <h5 class="list-title">Parts List</h5>      
      <span class="badge-secondary">CPU</span>
        <%= @build.parts_list.cpu %>
      <span class="badge-secondary">Cooler</span>
        <%= @build.parts_list.cpu_cooler %>
      <span class="badge-secondary">MB</span>
        <%= @build.parts_list.motherboard %>
      <span class="badge-secondary">RAM</span>
        <%= @build.parts_list.ram %>
      <span class="badge-secondary">Storage</span>
        <%= @build.parts_list.storage %>
      <span class="badge-secondary">GPU</span>
        <%= @build.parts_list.video_card %>
      <span class="badge-secondary">Case</span>
        <%= @build.parts_list.case %>
      <span class="badge-secondary">PSU</span>
        <%= @build.parts_list.power_supply %>
      <span class="badge-secondary">OS</span>
        <%= @build.parts_list.operating_system %>
      <span class="badge-secondary">Monitor</span>
        <%= @build.parts_list.monitor %>
    </ul>    
  </div>
  
  
  <div id="likes-container" class="card col-sm-6" style="width: 18rem;">
  <% if @build.user != current_user %>
    <%= render 'like_unlike_button', build: @build, :as => 'build' %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title">Description</h5>

      <p class="card-text" id="body-<%= @build.id %>"><%= excerpt(@build.description, @build.description[0], radius: 65)%>
      <button class="btn btn-secondary btn-sm js-more" data-id="<%= @build.id %>">More...</button></p>
    
    <section class="comments">
      <div id="list-comments-container">
        <h5 class="card-title">Comments</h5>
          <div class="container-fluid">
            <div class="card">
              <ul class="list-group list-group-flush comments-list">
                <%#= render :partial => 'comments/comments' %>
              </ul>
            </div>
          </div>
      </div>

      <% if @build.user != current_user %>
      <%= link_to "Leave a comment", "#", class:"btn-primary btn show-form" %>
        <div id="new-comment-container">  
        <div class="container-fluid">
          <div class="card">
            <ul class="list-group list-group-flush">
              <li class ="list-group-item">
                <%= render 'comments/comments_form' %>
              </li>
            </ul>  
          </div>
        </div> 
        </div>
      <% end %>
    </section>  
  </div>
  </div>
</div>