config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root to: 'home#index'

  resources :parts_lists, except: [:show]

  resources :builds, except: [:index] do
    get :index, on: :collection, :action => 'index_all'
  end

  resources :builds do
    resources :comments
  end

  resources :builds do
    resources :users do
      post "like",      to: "likes#create"
      delete "dislike", to: "likes#destroy"
    end 
  end

  resources :users do 
    resources :parts_lists, only: [:show, :index, :new, :edit, :update, :destroy]
    resources :builds, except: [:index] do
      get :index, on: :collection, :action => 'index_builds'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :parts_lists, dependent: :destroy
  has_many :builds, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_builds, through: :likes, source: :build

  def has_no_parts?
    parts_lists.empty?
  end

  def has_no_builds?
    builds.empty?
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @user}
    end
  end

  def destroy
    User.find(params[:id]).destroy
    session[:user_id] = nil
    flash[:success] = "Account successfuly deleted!"
    redirect_to root_path
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
	  <div class="col-md-2">
		  <div class="list-group text-secondary">
        <h1>User Profile</h1>
        <h4><%= @user.username %></h4><br>
        <h2>Account</h2>
        <h6>Builds</h6>
        <h4><%= @user.builds.count %></h4>
        <h6>Parts Lists</h6>
        <h4><%= @user.parts_lists.count %></h4>
        <h6>Comments</h6>
        <h4><%= @user.comments.count %></h4>
        <h6>Liked Builds</h6>
        <h4><%= @user.liked_builds.count %></h4>
        <h6>Member Since</h6>
        <h5><%= @user.created_at.strftime("%b %d, %Y") %></h5>
        <%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: 'btn btn-secondary btn-danger' %>                  
      </div>
    </div>
    <div class="column col-md-10">
      <div class="row">
        <div class="column col-md-6">
          <div class="list-group text-center">
            <h4 class="list-group-item list-group-item-action active">Parts Lists</h4>
              <% @user.parts_lists.each do |pl| %>
                <li class="list-group-item"><%= pl.name %></li>
              <% end %>        
          </div>
        </div>
        <div class="column col-md-6">
          <div class="list-group text-center">
            <h4 class="list-group-item list-group-item-action active">Builds</h4>
              <% @user.builds.each do |build| %>
                <%= link_to build.title, user_build_path(@user, build), class: "list-group-item list-group-item-action" %>
              <% end %>   
          </div>
        </div>
      </div>
      <div class="row">
        <div class="column col-md container-fluid">
          <div class="list-group text-center">
            <h4 class="list-group-item list-group-item-action active">Liked Builds</h4>
          </div>     
          
          <% @user.liked_builds.each_slice(2) do |builds| %>
          <div class="card-deck container-fluid">
            <% builds.each do |build| %>
              <div class="card bg-dark text-white text-center">
                <%= link_to image_tag(build.images.first, class: "card-img"), build_path(build) %>
                <h2 class="card-title"><%= build.title %></h2>
                <p class="card-text">by <%= build.user.username %></p>
              </div>
            <% end %>
          </div>
          <% end %>   
        </div>
      </div>
    </div>
  </div>
</div>