config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root to: 'home#index'

  resources :parts_lists, except: [:show]

  resources :builds, except: [:index] do
    get :index, on: :collection, :action => 'index_all'
  end

  resources :builds do
    resources :comments
  end

  resources :builds do
    resources :users do
      post "like",      to: "likes#create"
      delete "dislike", to: "likes#destroy"
    end 
  end

  resources :users do 
    resources :parts_lists, only: [:show, :index, :new, :edit, :update, :destroy]
    resources :builds, except: [:index] do
      get :index, on: :collection, :action => 'index_builds'
    end
  end

end

app/models/parts_list.rb
class PartsList < ApplicationRecord
  belongs_to :user
  has_many :builds

  validates :name,             presence: true
  validates :cpu,              presence: true
  validates :cpu_cooler,       presence: true
  validates :motherboard,      presence: true
  validates :ram,              presence: true
  validates :storage,          presence: true
  validates :video_card,       presence: true
  validates :case,             presence: true
  validates :power_supply,     presence: true
  validates :operating_system, presence: true
  validates :monitor,          presence: true
end

app/controllers/parts_lists_controller.rb
class PartsListsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_list, only: [:edit, :update, :destroy]
  before_action :find_user

  def index
    @user = User.find_by(id: params[:user_id])
    if params[:user_id]
      @parts_lists = User.find(params[:user_id]).parts_lists
    else
      @user = current_user
      @parts_lists = PartsList.all
    end
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @parts_lists}
    end
  end

  def new
    @parts_list = PartsList.new
  end

  def create
    @parts_list = current_user.parts_lists.build(parts_list_params)
    if @parts_list.save
      redirect_to(user_parts_lists_path(current_user), flash: { success: "Parts List Added!" })
    else
      
      render "new" 
      # redirect_to(new_user_parts_list_path(current_user), flash: { message: "Something went wrong, try again!" })
    end
  end

  def edit
  end

  def update
    if @parts_list.user == current_user
      @parts_list.update(parts_list_params)
      if @parts_list.save
        redirect_to(user_parts_lists_path(current_user), flash: { success: "Your list #{@parts_list.name} was successfully updated!" })
      else
        redirect_to(new_user_parts_list_path(current_user), flash: { message: "Something went wrong, try again!" })
      end
    else
      flash[:message] = "You don't have permission to do that"
      redirect_to root_path
    end
  end

  def destroy
    if @parts_list.user == current_user
      @parts_list.delete
      flash[:success] = "List deleted!"
      redirect_to user_parts_lists_path(current_user)
    else
      flash.now[:message] = "You don't have permision to do that!"
      redirect_to root_path
    end
  end

  private

    def parts_list_params
      params.require(:parts_list).permit(
        :name, 
        :cpu, 
        :cpu_cooler, 
        :motherboard,
        :ram, 
        :storage, 
        :video_card, 
        :case, 
        :power_supply, 
        :operating_system, 
        :monitor
      )
    end

    def find_list
      @parts_list = PartsList.find_by_id(params[:id])
    end

    def find_user
      @user = current_user
    end
end

app/helpers/parts_lists_helper.rb
module PartsListsHelper
end

app/views/parts_lists/_form.html.erb
<%= form_for @parts_list do |f| %>

    <% if @parts_list.errors.any? %>
    <% @parts_list.errors.full_messages.each do |message| %>
      <div class="alert alert-danger text-center"> 
        <%= message %>
      </div>
    <% end %>
    <% end %>
    
  <form class="form-horizontal">
    <div class="form-group row text-white">
      <%= f.label :name, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :name, class: "form-control col-sm-9" %>  
    </div>    
    <div class="form-group row text-white">
      <%= f.label :cpu, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :cpu, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :cpu_cooler, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :cpu_cooler, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :motherboard, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :motherboard, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :ram, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :ram, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :storage, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :storage, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :video_card, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :video_card, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :case, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :case, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :power_supply, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :power_supply, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :operating_system, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :operating_system, class: "form-control col-sm-9" %>
    </div>
    <div class="form-group row text-white">
      <%= f.label :monitor, class: "col-sm-3 col-form-label"%>
      <%= f.text_field :monitor, class: "form-control col-sm-9" %>
    </div>
    <div class="text-center">
      <%= f.submit class: 'btn-primary btn' %>
    </div>
  </form>      
<% end %>

app/views/parts_lists/_jumbotron.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">Parts List</h1>
  <p class="lead">In order to add your PC builds, you must have parts lists.</p>
  <hr class="my-4">
  <p>Add your first list here</p>
  <%= link_to "Get Started", new_user_parts_list_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/parts_lists/_parts_list_deck.html.erb
<nav class="navbar justify-content-end">
    <h3 class="text-xs-center m-y-3 text-white"><%= @user.username.capitalize %> Parts List's</h3>    
    <%= link_to "Add New", new_user_parts_list_path(current_user), class: 'btn btn-success ml-auto mr-2 font-weight-bold' %>
    <%= link_to "Start A New Build", new_user_build_path(current_user), class: 'btn btn-info mr-2 font-weight-bold' %>
  <div class="js-sort">
    <button class="btn btn-primary js-sort" data-sort="cpu">Sort By CPU</button>
  </div>
</nav>

<div class="parts-lists-group" data-id="<%= @user.id %>">
  <ul class="list-group text-center parts-lists" id="parts-lists">
  </ul>
</div>

app/views/parts_lists/edit.html.erb
<div class="container text-center">
  <h1>Edit <%= @parts_list.name %> List</h1>
</div>

<%= render 'form' %>

app/views/parts_lists/index.html.erb
<div class="container">

  <% if current_user.has_no_parts? %>
    <nav class="navbar justify-content-end">
      <h3 class="text-xs-center m-y-3 text-muted"><%= @user.username.capitalize %> Parts Lists</h3>
    </nav>   
    <%= render 'jumbotron' %>
  <% else %>
    <%= render 'parts_list_deck' %>
  <% end %>

</div>

app/views/parts_lists/new.html.erb
<div class="container text-center text-secondary">
  <h1>New Parts List</h1>
</div>

<%= render 'form' %>